project:
  type: website
  output-dir: docs

website:
  title: "SMORES Documentation"
  search: true
  repo-url: https://github.com/noaa-nwfsc/SMORES
  repo-actions: [issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Access.qmd
      - text: GUI Quickstart Guides
        menu: 
          - Full_Model_Creation.qmd
          - Save_A_Scenario.qmd
          - Load_A_Scenario.qmd
          - Delete_Scenario.qmd
      - text: Methods
        menu: 
          - Methods.qmd
          - Functions.qmd
      - Data.qmd
      - Questions.qmd 
      - text: Developers' Guides
        menu: 
          - Add_A_Layer.qmd
          - Add_An_AreaOfInterest.qmd
  page-footer: 
    right: Made with [Quarto](https://quarto.org/)

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    custom:
      body-secondary: "#000000"



