---
title: "SMORES Access Guide"
format: html
---

Here are a few tips for accessing the SMORES app and where to look if you have questions regarding the code. 

# How can I access the SMORES app?

There are 2 main avenues for accessing the SMORES App. The first option is accessing SMORES on the NOAA NMFS Posit Connect Test Instance. The App is hosted at this [link](https://test-connect.fisheries.noaa.gov/connect/#/apps/3e44db0d-bd12-49b2-bb7e-ace703306b12). The second option is to clone the SMORES Github [repository](https://github.com/noaa-nwfsc/SMORES){target="_blank"} and run the app on your local machine from R Studio. The repository contains all data, and code necessary to run the app. After you clone the repository you will select `Run App` after opening 1 of the following 3 files: ui.R, server.R, or global.R.

# What is the NOAA NMFS Posit Connect Test Instance?

Posit Connect is a publishing platform for R and Python-associated products. Products can be hosted publicly or internally, accessible to NOAA staff only.

# How do I get onto the Posit Connect Test Instance to use the app?

The Post Connect Test Instance is able to be accessed if you have a NOAA email account. It is important to note that in order to log in you must be connected to a NOAA network. This means you will either need to be on site and connected to WiFi/Ethernet or connected to the NOAA VPN. If you are not connected to these, the app will not load and you will get a message that states the request timed out. 

# Where can I see the back-end code of this app?

The [code](https://github.com/noaa-nwfsc/SMORES){target="_blank"} for this application is stored on the NMFS NWFSC Github Enterprise.