---
title: "Data Sources"
format: html
---

# Area of Interest Layers 

## Wind Energy Areas 

**Brief Description**: Wind Energy Areas were derived from wind energy area boundaries off the coasts of California and Oregon obtained from the Bureau of Ocean Energy Management (BOEM). These data sources were filtered and merged to include the following wind energy areas: Morro Bay, Humboldt, Coos Bay, and Brookings. 

**Accessed**:

California Wind Energy Area Boundaries: [ArcGIS Rest Service](https://services7.arcgis.com/G5Ma95RzqJRPKsWL/ArcGIS/rest/services/Wind_Lease_Boundaries__BOEM_/FeatureServer){target="_blank"}

Draft Oregon Wind Energy Area Boundaries: [Link](https://www.boem.gov/renewable-energy/state-activities/oregon-activities){target="_blank"}

**Units**: EPSG:3857

## OCS Planning Area 

**Brief Description**: Planning areas are used to support mostly the National Oil and Gas Program but also other BOEM Programs consisting of a schedule of lease sales indicating the size, timing, and location of proposed leasing activity the Secretary of Interior determines will best meet national energy needs. For oil and gas lease sales, the Program covers a five year period following its approval, and an area must be included in the current 5-Year Program in order to be offered for leasing. Section 18 of the OCS Lands Act prescribes the major steps involved in developing a 5-Year Program, including extensive public comment periods. These polygons are clipped to the Submerged Land Act Boundary and Continental Shelf Boundaries. These data were subsetted to only include planning areas that occurred in California, Oregon, and Washington. 

**Accessed**: [Marine Cadastre](https://hub.marinecadastre.gov/datasets/BOEM::ocs-planning-area-polygons/about){target="_blank"}

**Units**: These data were created in the applicable NAD83 UTM Projection and re-projected to WGS84 Geographic. 

**Citation**: Bureau of Ocean Energy Management (BOEM), Office of Strategic Resources (OSR), Geospatial Services Division (GSD)

# Habitat Layers

## Canyons

**Brief Description**: This dataset was created utilizing an objective system to inventory locations and names of large submarine canyons on the United States OCS in the Atlantic, Pacific, and Arctic Oceans and the Gulf of Mexico. The objective system utilized bathymetric data for average and maximum width, length and average and maximum depth of canyons to select ‘large’ submarine canyons for inclusion in this study. For the purposes of this study, submarine canyons were defined as “steep-walled, sinuous valleys with V-shaped cross sections, axes sloping outwards as continuously as river-cut land canyons and relief comparable to even the largest of land canyons”. One of the challenging portions of the selection process was the identification of individual canyons. While some canyons are spatially isolated from others and visually distinctive using various bathymetric data sources, others are more difficult to distinguish individually because of their proximity and overlapping or nearly overlapping dendritic patterning, especially in their shallower extents. Fortunately, a recent paper (Harris et al. 2014[1]) provided an authoritative description of many of these major canyons and was the starting point for development of the methods used in this study to determine the canyon boundaries. However, to develop a more objective methodology for this study, the basis for choosing the boundaries was based on defensible, accepted methods. In summary, the methods included: 1) examination of bathymetric datasets across all regions; 2) utilization of a series of tools within the Esri hydrology analysis Basin toolkit to extract the approximate Harris thalweg to define stream orders from the resulting flow accumulation output; 3) association of seafloor slope with canyons by examining the bathymetric raster for its cumulative frequency distribution of the slope values in SAS (2016) using PROC UNIVARIATE to sequentially eliminate the flatter slopes; 4) establishment of buffer spatial extents utilizing the 4.6th(2 Standard Deviations [SD]) percentile to determine the steepest slopes.

**Accessed**: [ArcGIS Rest Service](https://services.arcgis.com/bDAhvQYMG4WL8O5o/arcgis/rest/services/US_Submarine_Canyons/FeatureServer){target="_blank"
}

**Spatial Reference**: EPSG:4326 

**Citation**: CSA Ocean Sciences Inc. (CSA), De Leo, F.C., and Ross, S.W. 2019. Large Submarine Canyons of the United States Outer Continental Shelf Atlas dataset. U.S. Dept. of the Interior, Bureau of Ocean Energy Management, Environmental Studies Program, Washington, DC, under Contract Number 140M0119F0009.

## Deep Sea Coral Robust High Suitability

**Brief Description**: BOEM-funded Cross-Shelf Habitat Suitability Modeling of Coral and Sponge Habitat provides spatial predictions of relative habitat suitability for a number of coral and sponge taxa (Poti et al. 2020). In order to examine patterns of habitat suitability across multiple taxa, the Poti et al. (2020) study developed two aggregate products, both of which we felt would be most useful to the NCCOS model: 1) Number of deep-sea coral taxa associated with hard substrate that were predicted to have high habitat suitability, and 2) Number of deep-sea coral taxa associated with hard substrate that were predicted to have robust-high habitat suitability. Instead of integrating habitat suitability models for individual taxa, these two aggregate products show the number of taxa predicted to have high or robust-high habitat suitability, respectively, for each grid cell. The Robust High data product is available within this application. The aggregate products exclude sea pens because most sea pen species do not associate with hard substrate, and exclude sponges due to the low taxonomic specificity, and consequent broad substrate affinities, of input records. Like many deep-sea corals, some sponges, especially glass sponges (e.g., Heterochone calyx) provide structural habitat for other organisms including some groundfishes. Rescaling was conducted using the fuzzy logic Z-shaped
membership function from 0.0–1.

**Accessed**: [ArcGIS Rest Service](https://gis.ngdc.noaa.gov/arcgis/rest/services/nccos/USWestCoast_DeepSeaCoralsSponges/MapServer/256){target="_blank"}

**Citation**: National Oceanic and Atmospheric Adminstration (NOAA) National Centers for Coastal Ocean Science (NCCOS)

## Seeps

**Brief Description**: Methane bubble streams identified during multibeam sonar surveys often indicate the location of active methane seeps and associated seep communities on the seafloor. We curated data layers from recent publications that summarize the point locations of these bubble streams. Recent remotely operated vehicle (ROV) surveys have confirmed active gas venting on the seafloor for some of these locations, as well as the presence of methane seep communities. 

**Accessed**: Unpublished

**Units**

**Citation**

## Shelf Break

**Brief Description**: The continental shelf break is a physiographic feature that is sometimes represented as a particular isobath but is more appropriately delineated from geophysical data. We extracted the line feature representing the boundary between the "shelf" and "slope" physiographic classes from the Goldfinger et al. 2014 Surficial Geologic Habitat v.4.0 layer. The line between these polygons was extracted and buffered by 10-km on either side. 

**Accessed**: 

**Units**

**Citation**: Goldfinger et al. 2014
Surficial Geologic Habitat v.4.0; https://www.boem.gov/sites/default/files/environmentalstewardship/Environmental-Studies/PacificRegion/Studies/BOEM2014-662-Vol-1.pdf

## EFHCA

**Brief Description**: Shapefile depicting boundaries of EFH conservation areas. This shapefile is not a legal boundary but is rather a geospatial representation of what is published in the Code of Federal Regulations (50 CFR 660).

**Accessed**: NMFS EFH resource [site](https://www.fisheries.noaa.gov/resource/map/essential-fish-habitat-groundfish-and-salmon){target="_blank"}. 

**Units**

**Citation**

## EFHCA 700 fathoms

**Brief Description**: Shapefile depicting boundary of the "Seaward of the 700-fm bottom trawl closure" EFH conservation area. This shapefile is not a legal boundary but is rather a geospatial representation of what is published in the Code of Federal Regulations (50 CFR 660).

**Accessed**

**Units**

**Citation**

## HAPC AOI

**Brief Description**: Habitat Areas of Particular Concern Areas of Interest. Areas of interest are discrete areas that are of special interest due to their unique geological and ecological characteristics. The following areas of interest are designated HAPCs:

Off of Washington: All waters and sea bottom in state waters shoreward from the three nautical mile boundary of the territorial sea shoreward to MHHW.

Off of Oregon: Daisy Bank/Nelson Island, Thompson Seamount, President Jackson Seamount.

Off of California: all seamounts, including Gumdrop Seamount, Pioneer Seamount, Guide Seamount, Taney Seamount, Davidson Seamount, and San Juan Seamount; Mendocino Ridge; Cordell Bank; Monterey Canyon; specific areas in the Federal waters of the Channel Islands National Marine Sanctuary; specific areas of the Cowcod Conservation Area.

**Accessed**: 

**Units**

**Citation**

## HAPC Rocky Reef

**Brief Description**: Habitat Areas of Particular Concern Rocky Reefs. The rocky reefs HAPC includes those waters, substrates and other biogenic features associated with hard substrate (bedrock, boulders, cobble, gravel, etc.) to MHHW. 

**Accessed**: 

**Units**

**Citation**

# Species Layers

## ESA Critical Habitat for Southern Resident Killer Whales

**Brief Description**

**Accessed**: [Data reference](https://www.fisheries.noaa.gov/action/critical-habitat-southern-resident-killer-whale){target="_blank"}

**Units**

**Citation**: NOAA NMFS

## ESA Critical Habitat for Leatherback Sea Turtles

**Brief Description**

**Accessed**: Unpublished

**Units**

**Citation**

## ESA Critical Habitat for Humpback Whales - Mexico and Central DPS

**Brief Description**

**Accessed**: Unpublished

**Citation**: NOAA NMFS

## Biologically Important Area - Blue Whale

**Brief Description**

**Accessed**: Unpublished

**Units**

**Citation**: NOAA NMFS

# Fisheries Layers

## At-Sea Hake Mid-Water Trawl

**Brief Description**: Logbooks from PacFIN via the NMFS NWSC observer program

**Accessed**: Unpublished

**Units**

**Citation**

## Shoreside Hake Mid-Water Trawl

**Brief Description**: Logbooks from PacFIN via the observer database and from ODFW, NMFS NWFSC Observer Program

**Accessed**: Unpublished

**Units**

**Citation**

## Groundfish Bottom Trawl

**Brief Description**: Logbooks from PacFIN via the NMFS NWSC observer program database

**Accessed**: Unpublished

**Units**

**Citation**

## Groundfish Pot Gear

**Brief Description**

**Accessed**: Unpublished

**Units**

**Citation**

## Groundfish Long Line Gear

**Brief Description**

**Accessed**: Unpublished

**Units**

**Citation**

## Pink Shrimp Trawl

**Brief Description**: ODFW logbook, PacFIN

**Accessed**: Unpublished

**Units**

**Citation**

## Dungeness Crab

**Brief Description**: ODFW logbook, PacFIN

**Accessed**: Unpublished

**Units**

**Citation**

## Commercial Troll/Hook and Line Albacore

**Brief Description**: NMFS SWFSC, PacFIN

**Accessed**: Unpublished

**Units**

**Citation**

## Charter Vessel Albacore Troll/Hook and Line

**Brief Description**: 

**Accessed**: Unpublished

**Units**

**Citation**

## Trawl Fisheries 

**Brief Description**: Trawl fisheries (bottom and mid-water trawl), in particular, have little flexibility in where they fish due to their operational logistics. The gear requires large spaces for maneuverability and is incompatible with other structures and cables/mooring lines in the water, including what would likely be infrastructure for floating offshore wind platforms and anchors. The targeted species are also associated with locations along the shelf and slope and specific depth ranges. Therefore, these fisheries are especially vulnerable to fragmentation of fishing grounds. Four trawl fisheries operate within the two OR Call Areas: Groundfish bottom trawl (Federal), At-sea hake mid-water trawl (Federal), Shoreside hake mid-water trawl (Federal), Pink shrimp trawl (State).

For the four trawl fisheries, NMFS and ODFW calculated the regions where the top 75% of the ranked importance values occur. 

**Accessed**: Unpublished

**Units**

**Citation**: If you have additional questions please refer to the Fisheries Considerations provided by NOAA's National Marine Fisheries Service (NMFS) and Oregon Department of Fish and Wildlife (ODFW) included in the NCCOS Spatial Modeling of Oregon Call Areas as [Appendix E](https://www.boem.gov/sites/default/files/documents/renewable-energy/state-activities/Appendix%20B_NCCOS%20Final%20WEA%20Report_Oregon.pdf){target="_blank"}. 

# Scientific Surveys Layers

## Fixed Surveys

**Brief Description**: This data product is intended to help communicate the geographic extent and operations of NOAA Fisheries offshore ship-based scientific surveys along the U.S. west coast (California, Oregon, Washington). NOAA Fisheries conducts numerous scientific surveys to inform the status of fish stocks and protected resources. For the West Coast Region, more than a dozen surveys are conducted routinely across the continental margin, focusing either on pelagic or demersal species or the ecosystem as a whole. These surveys collect a variety of biological and environmental data to provide a synoptic view of the habitats and ecosystems for which the target species inhabit. The surveys utilize varying designs including fixed stations where a number of operations are centered, transect lines where fishery acoustic data are continually collected, and stratified random sampling, to name a few.

Fixed surveys are defined by NOAA Fisheries as those with fixed station designs, where sampling occurs at the same locations across the time frame of the survey. Survey locations (points) and transects (lines) were bufferred to represent the effective sampling area for these stations and transects.

**Accessed**

**Units**

**Citation**

## Periodic Surveys

**Brief Description**: This data product is intended to help communicate the geographic extent and operations of NOAA Fisheries offshore ship-based scientific surveys along the U.S. west coast (California, Oregon, Washington). NOAA Fisheries conducts numerous scientific surveys to inform the status of fish stocks and protected resources. For the West Coast Region, more than a dozen surveys are conducted routinely across the continental margin, focusing either on pelagic or demersal species or the ecosystem as a whole. These surveys collect a variety of biological and environmental data to provide a synoptic view of the habitats and ecosystems for which the target species inhabit. The surveys utilize varying designs including fixed stations where a number of operations are centered, transect lines where fishery acoustic data are continually collected, and stratified random sampling, to name a few.

Periodic surveys are defined by NOAA Fisheries as those with random station designs, where sampling occurs periodically or at randomly-selected locations across the survey domain.

**Accessed**

**Units**

**Citation**

# Submarine Cable Layers

## Submarine Cables

**Brief Description**: These data show the general location of commercial and research submarine cables within U.S. waters. The majority of these cables are for telecommunications, and the remaining are for power transmission. The geographic footprint for each cable may vary and is dependent on the original source data. In the near shore, cables are routinely buried below the seabed. Offshore, below a certain water depth, they are placed directly on the seabed. A submarine cable area may contain one or more physical cables, and 30 CFR 585.301 defines a minimum 100-foot-wide right of way grant on each side of a cable.

**Accessed**: [Marine Cadastre](https://hub.marinecadastre.gov/datasets/noaa::submarine-cables/about){target="_blank"}, [ArcGIS Rest Service](https://coast.noaa.gov/arcgis/rest/services/Hosted/SubmarineCables/FeatureServer){target="_blank"}

**Units**: EPSG:4269

**Citation**: Office for Coastal Management, 2025: Submarine Cables, [https://www.fisheries.noaa.gov/inport/item/66190](https://www.fisheries.noaa.gov/inport/item/66190){target="_blank"}.


