---
title: "Methods"
format: html
---
## Background

The SMORES application was built from the spatial planning processes developed for *A Wind Energy Area Siting Analysis for the Oregon Call Areas* and the *Aquaculture Opportunity Atlas's*. These projects provided the marine spatial planning framework that is used by this application.

- Additional Information about *A Wind Energy Area Siting Analysis for the Oregon Call Areas* can be found in this [documentation](https://www.boem.gov/sites/default/files/documents/environment/BOEM_2024-015.pdf){target="_blank"}. This groups work can be cited as: Carlton J, Jossart JA, Pendleton F, Sumait N, Miller J, Thurston-Keller J, Reeb D, Gilbane L, Pereksta D, Schroeder D, Morris Jr JA. 2024. A wind energy area siting analysis for the Oregon Call Areas. Camarillo (CA): U.S. Department of the Interior, Bureau of Ocean Energy Management. 237 p. Report No.: OCS Study BOEM 2024-015.

## Components

This application is broken up into different components. These components are carried through the application and provide clarity in when different functions are applied. These components are as follows:

- **Individual Layers**

Individual Layers are any layer or data set that is being used in a model run before it is combined with any additional layers. 

- **Submodel Components**

Submodel components are the subgroups of each submodel. These are the result of combining individual layers that all fall within the same general category. An example of a submodel component for the application would be the combined individual layers that fall within the habitat category. This combination of indivudal layers would result in the habitat submodel component of the natural resources submodel. 

- **Submodels**

Submodels are the result from combining submodel components. An example of a submodel for the application would be the natural resources submodel which is made up of two submodel components: habitat, and species. 

- **Full Model**

The full model is the result of combining submodels. In the application you can choose which submodels you would like to have included in the full model. 

## Pre-processing 

To generate an individual data layer data sources are processed before they are loaded into the app. This pre-processing step ensures that data layers are in the correct coordinate reference system, overlaid with the grid, and ready to be digested by the application. Pre-processing is done with two main files. [Data_productions.R](https://github.com/noaa-nwfsc/SMORES/blob/main/data_production.R){target="_blank"} prepares the raw data files while [preprocess_spatial_data()](https://github.com/noaa-nwfsc/SMORES/blob/main/R/preprocess_spatial_data.R){target="_blank"} prepares the files for application compatibility. The key steps that are taken by these functions are the following:

- 2 km grid for the west coast of the United States is accessed

- [St_intersection()](https://r-spatial.github.io/sf/reference/geos_binary_ops.html){target="_blank} is run between the individual layer and the 2 km grid to identify grid cells that have data for the individual layer

- Grid cells that have values are selected and fitted with a placeholder value (this applies for any layer that is a presence/absence data value)

- New columns are made for each value a user might select and grid cells are populated with these values

- Data frame is pivoted to the long format so that each grid cell has a list of values available to it if the grid cell had a presence of data

- Data is transformed to be in the WGS 84 coordinate system for compatibility with [leaflet()](https://leafletjs.com/){target="_blank"} mapping

- Data is saved as a [geoparquet](https://geoparquet.org/){target="_blank"} file format. This format was chosen for its ability to efficiently store large spatial data files.

Data is now prepared to be loaded into the application. 

## Score Options

One of the main goals of the SMORES application was to allow for NMFS to model the impacts of different scoring scenarios before recommending scoring scenarios to BOEM. In order to achieve this different individual layers within the app have score drop down menus to allow for different score selection options. Based on how data were created and the best practices for that data type individual layers have three options for the scores presented: static, z-membership, and ranked importance. 

### Static Score

Static scored data is selected when data are represented with a single value (ie. 0, 0.9, etc.). These data represent the presence or absence of an individual layer for a given 2x2-km cell that is then assigned a value. These values have been standardized within the application between 0 to 1 with a step of 0.1, or values to represent constraints such as 0.01, or 0.001. Scores are to be determined by the individual who is running model scenarios. However, there are scoring recommendations and guidelines from the Oregon siting exercise. Recommended scoring scenarios are presented on the application for the component you are viewing (ie. recommended species scores are shown on the species sub-tab of the natural resource submodel).

### Z-Membership

Z-membership data is selected when data has been re-scaled using a fuzzy logic Z-shaped membership function from 0 to 1. The Z membership function is applied in the [data_production.R file](https://github.com/noaa-nwfsc/SMORES/blob/ecb863dbe7226e34f3212eab3c53b90d42cc905c/data_production.R#L160){target="_blank"}. 

### Ranked Importance

Ranked Importance data is used to represent fisheries data. Per the fisheries data and methods provided by NMFS in Appendix E of the [Oregon Final Wind Energy Areas Report](https://www.boem.gov/sites/default/files/documents/renewable-energy/state-activities/Appendix%20B_NCCOS%20Final%20WEA%20Report_Oregon.pdf){target="_blank"} ranked importance was calculated by:

Fishing location information and duration fished were extracted or calculated from State and Federal logbook and Federal observer program datasets for each fishing event for each of the nine fisheries. Straight lines were drawn between the fishing start and end geocoordinates to create fishing event lines when both values were available; point locations were created when only a single fishing event geocoordinate was available. Each line or point location was matched to corresponding Pacific Fisheries Information Network (PacFIN) fish ticket information to retrieve inflation-adjusted ex-vessel (in 2020 USD) revenue derived from each fishing event. These lines and points of fishing effort and revenue were then overlaid and summarized on a 2x2-km grid. 

Exploratory analyses suggested that highly skewed distributions of fishing effort and revenue, in which a very small number of grid cells had exceptionally high values of effort and/or revenue, would grossly underestimate the amount of ocean space used by these nine fisheries. In order to account for these skewed distributions, we rank-transformed the fishing effort and revenue data. In order to combine and capture the most important characteristic (either ‘effort’ or ‘revenue’) of each fishery for each grid cell, we normalized (between 0 and 1) the rank-transformed effort and revenue data and then selected the highest normalized value for each grid cell. We term this final metric “Ranked Importance”. 

## Individual layers to submodel components

### Geometric Mean

The [geometric
mean](https://github.com/noaa-nwfsc/SMORES/blob/main/R/calculate_geometric_mean_combined.R){target="_blank"}
equation used was:

$$\text{g} = \sqrt[n]{x_1 \times x_2 \times \ldots \times x_i}$$

<center>
n = number of variables<br> x₁ = variable 1<br> x₂ = variable
2<br> xᵢ = additional variables

*each variable represents individual layer scores for that 2km cell (an example of an individual layer score would be EFHCA, BIA blue whale, submarine cables, etc.)
</center>

### Lowest Value

The
[lowest](https://github.com/noaa-nwfsc/SMORES/blob/main/R/calculate_lowest_combined.R){target="_blank"}
equation used was:

$$\text{l} = \min(x_1, x_2, \ldots, x_i)$$

<center>
x₁ = variable 1<br> x₂ = variable 2<br> xᵢ = additional
variables

*each variable represents individual layer scores for that 2km cell (an example of an individual layer score would be EFHCA, BIA blue whale, submarine cables, etc.)
</center>

### Product

The
[product](https://github.com/noaa-nwfsc/SMORES/blob/main/R/calculate_product_combined.R){target="_blank"}
equation used was:

$$\text{p} = x_1 \times x_2 \times \ldots \times x_i$$

<center>
x₁ = variable 1<br> x₂ = variable 2<br> xᵢ = additional
variables

*each variable represents individual layer scores for that 2km cell (an example of an individual layer score would be EFHCA, BIA blue whale, submarine cables, etc.)
</center>

## Components to Combined Submodels

### Geometric Mean

The [geometric
mean](https://github.com/noaa-nwfsc/SMORES/blob/main/R/calculate_geometric_mean_combined.R){target="_blank"}
equation used was:

$$\text{g} = \sqrt[n]{x_1 \times x_2 \times \ldots \times x_i}$$

<center>
n = number of variables<br> x₁ = variable 1<br> x₂ = variable
2<br> xᵢ = additional variables

*each variable represents component scores for that 2km cell (an example of a component score would be habitat, species, surveys, etc.)
</center>


## Combined submodels to Full Model

### Weighted Geometric Mean

To generate the full model map a [weighted geometric
mean](https://github.com/noaa-nwfsc/SMORES/blob/main/R/create_full_model_map.R){target="_blank"}
calculation was used:

$$\text{wg} = {x_1^{w_1} \times x_2^{w_2} \times \ldots \times x_i^{w_i}}^ 1/{w_1}+{w_2}+{w_i}$$

<center>
x₁ = variable 1<br> x₂ = variable
2<br> xᵢ = additional variables<br> w₁ = weight for variable 1<br> w₂ =
weight for variable 2<br> wᵢ = weights for additional variables

*each variable represents a submodel score for a 2km cell (an example of a submodel would be natural resource, fisheries, and industry and operations)
</center>

