---
title: "SMORES Access Guide"
format: html
---

Here are a few tips for accessing the SMORES app and where to look if you have questions regarding the code. 

# Where can I go to access the SMORES app?

The SMORES app is currently accessible on the NOAA NMFS Posit Connect Test Instance. The App is hosted at this [link](Melissa insert link here). 

# What is the NOAA NMFS Posit Connect Test Instance?

Posit connect is a publishing platform for R and Python-associated products. Products can be hosted publicly or internally, accessibile to NOAA only.

# How do I get onto the Posit Connect Test Instance to use the app?

The Post Connect Test Instance is able to be accessed if you have a NOAA email (affiliates, and federal). Is it important to note that in order to log in you must be on a NOAA connection. This means you will either need to be on site and connected to Wifi/ethernet or connected to the NOAA VPN. If you are not connected to these, the app will not load and you will get a message that states the request timed out. 

# Where can I see the back-end code of this app?

The code for this application is stored on the NMFS NWFSC Github Enterprise. The repository is stored [here](https://github.com/noaa-nwfsc/SMORES).